name: Deploy to gh-pages
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: .env
        env:
          SASS_PATH: node_modules:src
      - name: Build project
        run: yarn build
      - name: Export project
        run: yarn export
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Build directory to deploy
          build_dir: ./out
          jekyll: false